name: litesql
description: SQLite with single table ORM.
repository: https://github.com/yangentao/litesql
homepage: https://github.com/yangentao/litesql
version: 2.0.3

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.9.4
  println: ^1.0.4
  entao_dutil: ^2.0.5
  entao_log: ^1.2.8
  entao_lint: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
