name: litesql
description: SQLite with ORM.
repository: https://github.com/yangentao/litesql
homepage: https://github.com/yangentao/litesql
version: 3.1.1

environment:
  # Inference using bounds, generic used in TableOf class
  sdk: ^3.7.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  sqlite3: ^3.1.1
  println: ^1.0.4
  entao_dutil: ^2.3.2
  entao_log: ^1.2.8
  entao_lint: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
